[package]
name = "jwtrs"
version = "0.0.1"
authors = [ "Tan Quach <tan.quach@gmail.com>" ]

[dependencies]
iron = "0.4"
router = "0.4"
serde = "0.8"
bodyparser = "0.4.1"
mime = "0.2"
rustc-serialize = "0.3"